/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-12-08 20:36:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import uk.co.luciditysoftware.campervibe.domain.entities.Booking;
import uk.co.luciditysoftware.campervibe.domain.entities.Vehicle;
import java.util.Map;
import java.util.UUID;
import uk.co.luciditysoftware.campervibe.domain.entities.Vehicle;

public final class makeBookingForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/base.jspf", Long.valueOf(1448810352452L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.2.jar", Long.valueOf(1448756157400L));
    _jspx_dependants.put("jar:file:/C:/Code/CampervibeJava/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Campervibe/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.2.jar!/META-INF/c.tld", Long.valueOf(1343816218000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("uk.co.luciditysoftware.campervibe.domain.entities.Booking");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("uk.co.luciditysoftware.campervibe.domain.entities.Vehicle");
    _jspx_imports_classes.add("java.util.UUID");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;


    @SuppressWarnings("unchecked")
    Map<UUID, Vehicle> vehicleDatabase =
            (Map<UUID, Vehicle>)request.getAttribute("vehicleDatabase");

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Booking Form</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"POST\" action=\"booking\" role=\"form\" class=\"form-horizontal\" >\r\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"make\"/>\r\n");
      out.write("\t\t<div class=\"form-group\" >\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\" for=\"vehicleId\">Vehicle</label>\r\n");
      out.write("\t        <div class=\"col-sm-6\">\r\n");
      out.write("\t        \t<select id=\"vehicleId\" name=\"vehicleId\" class=\"form-control\">\r\n");
      out.write("\t        \t");

	        		for(UUID id : vehicleDatabase.keySet())
                	{
	                    String idString = id.toString();
	                    Vehicle vehicle = vehicleDatabase.get(id);
	                    
      out.write("<option value=\"");
      out.print( idString );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( vehicle.getName() );
      out.write("</option>");

                	}
	        	
      out.write("</select>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\" >\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\" for=\"startDate\">Start Date</label>\r\n");
      out.write("\t        <div class=\"col-sm-6\">\r\n");
      out.write("\t        \t<input id=\"startDate\" name=\"startDate\" type=\"text\" class=\"form-control\" />\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\" >\r\n");
      out.write("\t\t\t<label class=\"control-label col-sm-3\" for=\"endDate\">End Date</label>\r\n");
      out.write("\t        <div class=\"col-sm-6\">\r\n");
      out.write("\t        \t<input id=\"endDate\" name=\"endDate\" type=\"text\" class=\"form-control\" />\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group\">        \r\n");
      out.write("\t        <div class=\"col-sm-offset-3 col-sm-9\">\r\n");
      out.write("\t            <button type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
